# Generated by Django 5.0.2 on 2024-02-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='employee_id',
            field=models.CharField(default='XYz', max_length=10),
        ),
    ]
