# Generated by Django 5.0.2 on 2024-02-29 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_application_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='type',
            new_name='leave',
        ),
    ]
