# Generated by Django 5.0.2 on 2024-02-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=None, max_length=18),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_name',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
