# Generated by Django 5.0.2 on 2024-02-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_password_alter_employee_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_name',
            field=models.CharField(max_length=15),
        ),
    ]
