# Generated by Django 5.0.2 on 2024-02-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
