# Generated by Django 5.0.2 on 2024-02-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='descp',
            field=models.TextField(max_length=200),
        ),
    ]
