# Generated by Django 5.0.2 on 2024-02-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
